### PR TITLE
fix to check the curl result in http_request

### PR DESCRIPTION
**Pull request by takumin**

### CODE REVIEW

**Comment by k0kubun** [comment]
Oh, good catch. Thanks!

**Comment by k0kubun** [comment]
I like this, but maybe this is not compatible itamae?

**Comment by takumin** [comment]
Sorry, I did not test ...
And maybe itaema has not checked for errors.

**Comment by k0kubun** [comment]
Basically mitamae keeps the compatibility with itamae. How about adding an optional boolean attribute which allows this feature?

**Comment by takumin** [comment]
That looks better. Is boolean attribute name check_error OK?

**Pull request merged**
