### PR TITLE
Version 1.5.2

### PR DESCRIPTION
**Pull request by eagletmt**
@k0kubun Could you release a new version for #66 ? (or can I make a new release?)

### CODE REVIEW

**Comment by k0kubun** [comment]
> Could you release a new version for #66 ? 

Sure.

> (or can I make a new release?)

I have a plan to automate that later, but it's not now.

**Comment by k0kubun** [comment]
I changed your collaborator permission from "Write" to "Admin". Now I'm making a new release, but next time at least you can manually release it by yourself using `./release.sh`.

**Comment by k0kubun** [comment]
done https://github.com/itamae-kitchen/mitamae/releases/tag/v1.5.2

**Comment by eagletmt** [comment]
Thanks!

**Pull request merged**
